### PR TITLE
refactor: organize entries in icons_*

### PR DESCRIPTION
**Pull request by GR3YH4TT3R93**
refactor: organize entries in icons_ext.go

refactor: organize entries in icons_files.go

refactor: organize entries in icons_map.go

refactor: organize entries in icons_sub_ext.go

### CODE REVIEW

**Comment by GR3YH4TT3R93** [comment]
If there's an issue with this pull request like wanting the commits broken up, just lmk and I'd be happy to make the necessary changes

**Comment by canta2899** [comment]
Hi! No problem, sorry for replying late! 😄

**Comment by GR3YH4TT3R93** [comment]
All good! This pull request took me longer to get to than I'd like as well lol

**Comment by canta2899** [comment]
Thank you again! I honestly wouldn't have been able to find enough courage to do it  😆

**Pull request merged**
